[package]
name = "mexc_pb_ws_test"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.26.2"
tungstenite = "0.26.2"
futures-util = "0.3"
url = "2"
prost = "0.13.5"
bytes = "1"

[build-dependencies]
prost-build = "0.13.5"
